# Running Sessions

## Pre-Session 
\testbf{Recruitment}

•	All recruitment is conducted through SONA

\testbf{Scheduling}

•	Slots are scheduled through SONA

•	Each slot is 1 hour

•	Schedule at least 30 mins (Preferably 1 hour) between slots

•	Make sure Slot is marked on “Bear Den” Calendar

•	Once a slot is filled, send Scheduling Email (see email templates on Box)

•	For slot filled >1 week in advance, send reminder email 24-48hrs prior to session


## During Session
Preparation

•	Arrive at least 15 minutes prior to the scheduled session start time.

•	Materials:
  
  •	Consent Form (x2)
  
  •	iPad
  
  •	Electrodes (x5)
  
  •	Gauze & Alcohol wipe (x3)
  
  •	EDA (isotonic/white) paste (in syringe)
  
  •	ECG (green) Gel

•	Make sure both the Stimulus and Physio Computers are On

•	Turn on MP160

•	Make sure Wi-Fi is off

•	Open Acqknowledge and secet ‘TRAP_Physio_Template’

\testbf{Consent}

•	Greet participant and walk them into Bear Den

•	Offer participant a mask if they do not have one

•	Briefly Describe the study to participants
  
  •	i.e., “In this study we will first ask you to complete some questionnaires. Then we will         attach some sensors to your torso and hand, that allow us to measure how your body reacts          during the study. You will then watch some videos and rate how you are feeling throughout. The     session can last up to 1 hour.”

•	Allow the participant to read through the consent form

•	Check if/answer any questions the participant might have

•	Have you and the participant sign and date both copies of the consent form

  •	Keep one copy for our records; Have them take one copy for theirs

\testbf{Questionnaires}

•	Open the REDCap Questionnaires on the iPad

•	Hand the participant the iPad and ask them to complete the questionnaires

  •	You can let them know:

    •	Each questionnaire will automatically proceed to the next

    •	If they have any questions, they can ask you for clarification

    •	It should take approximately 15 minutes

•	When the participant has completed the questionnaires, they will return the iPad to you.

\testbf{Physiological Hook-up}

•	Ask the participant if they need to use the rest room

•	Collect Height and Weight measurements (enter into REDCap).

•	Ask the participant if they have any skin allergies or sensitives

•	Summarize/explain the physiology procedure to the participant

  •	i.e., “Ok, so now I am going to place some sensors on your body. The sensors will stick to         your skin but can be easily peeled off. I will place one sensor on your right collarbone, two      on your lower rib cages, and two on the palm of your non-dominant hand. Before place each          sensory, I will clean the area with an alcohol wipe and some gauze. We will also place a           respiration belt around torso. I will walk you through everything as we go, but if you have any     questions or anything feels uncomfortable, don’t hesitate to let me know.”

•	Place ECG Electrodes:

  •	Find where you will place sensor

  •	Clean the area with the alcohol wipe and then gauze

  •	Apply a small dot of electrode gel to the sensor

  •	Stick the sensor to the skin

  •	Repeat for all 3 spots

•	Place Respiration belt:

  •	It should fit semi-tightly around the torso, just above rib-ECG electrodes, but below              sternum. Plastic piece in front and centered. 

      •	It should NOT be uncomfortably tight

      •	Remember when the participant sits, the belt will likely become slightly tighter

•	Have Participant sit in chair (in front of stimulus computer).

•	Place EDA electrodes

  •	Apply 0.2 mL of isotonic paste to each EDA electrode

  •	Do NOT clean hand with alcohol

  •	Place the two electrodes with paste on the palm of the participant’s non-dominant hand

    •	Do not press on the center when placing – this will cause paste to squeeze out

•	Attached leads to electrodes

  •	ECG & Respiration attach to same transmitter

  •	EDA has its own transmitter (attaches to wrist)

•	Check Signals in Acqknowledge

\testbf{TRAP Task}

•	Open Matlab

•	Make sure you are in the correct folder

  •	/Users/brainandbodylabmacmini2/Desktop/TRAP_Task

•	In the Console Window type: TRAP_Task(‘trap_XXX’)

  •	i.e., Participant 1 would be ‘trap_001’

•	Press Enter

•	Walk participant through instructions

•	Make sure participant has headphones on

•	Rest of task will proceed automatically

•	During the task monitor both the physiology and participant

  •	Make notes throughout:

    •	i.e., Physio signal looked weird, participant talked/laughed, etc.

    •	Try to note times as well to make it easier to examine post-hoc

•	After Task is Complete, ask Video Familiarity Questions

\testbf{Matlab Troubleshooting:}

•	Close task: Ctr + C -> sca -> Enter

•	Move up a directory: cd ..

\testbf{Clean-up/Debrief}

•	Stop the physio recording

•	Detect the wires from the participant

•	Have participant remove sensors

  •	They can do this themselves or you can help if they prefer

    •	“Ripping it off like a Band-Aid” is NOT best approach typically

    •	Hold the skin, while peeling up, usually works best – if sensors are particularly sticky

•	Ask the participant if they have any questions about the study

•	Let them know they are all set and that their SONA credit should show up in within 24 hours

## Post-Session

\testbf{Data Back-up}

•	Make sure to save Physio Data

  •	Use naming convention: ‘trap_XXX_physio.acq’

•	Upload/back-up both the behavioral data and physio file to Box

  •	Arousal Data: BABLab/Studies/TRAP/Data/Behavioral

  •	Physio Data: BABLab/ Studies/TRAP/Data/Physio

•	Store any paper copies (i.e., consent forms) in locked cabinet

  •	All consent forms should be stored in alphabetical order, by last name

•	Update participant tracking sheet

